spring:
  application:
    name: drcb-cloud-task
  datasource:
    url: jdbc:sqlserver://158.82.100.112;databasename=CloudTask
    username: sa
    password: drcb@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql-server
#  boot:
#    admin:
#      client:
#        url: http://localhost:8081
#        instance:
#          prefer-ip: true
server:
  port: 8080


#feign:
#  hystrix:
#    enabled: true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000
#hystrix: 
#  command: 
#    default: 
#      execution: 
#        isolation: 
#          thread: 
#            timeoutInMilliseconds: 10000
#ribbon: 
#  ReadTimeout: 120000
#  ConnectTimeout: 3000
   
info: 
  version: ${project.version}
  name: ${project.artifactId}

#admin
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      base-path: /
#  endpoint:
#    health:
#      show-details: always
      
      
#eureak      
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


#log
logging:
  level: 
    root: warn
    com.deqingbank:  debug
    org.springframework.web: warn
    org.springframework.cloud.netflix.eureka: warn
    feign: debug
    com.netflix.hystrix: debug
     